wandb_version: 1

Ne:
  desc: null
  value: 558
Nv:
  desc: null
  value: 183
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    python_version: 3.10.8
    start_time: 1668849014.272421
    t:
      1:
      - 1
      - 9
      - 55
      - 77
      2:
      - 1
      - 9
      - 55
      - 77
      3:
      - 7
      - 23
      4: 3.10.8
      5: 0.13.5
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 0.0
beta:
  desc: null
  value: 0.0
channels:
  desc: null
  value: 4
de:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.1
dv:
  desc: null
  value: 4
graph:
  desc: null
  value: DiGraph with 183 nodes and 558 edges
input_dim:
  desc: null
  value: 1703
input_dropout:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.0001
true_sheaf:
  desc: null
  value: None
