wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.7546923412699057
dv:
  value: 3
first_hidden:
  value: 1000
free_potential:
  value: true
input_dropout:
  value: 0.274333385812388
layers:
  value: 4
second_hidden:
  value: 100
