wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.25664410801542425
dv:
  value: 3
first_hidden:
  value: 1000
free_potential:
  value: false
input_dropout:
  value: 0.6161562484777097
layers:
  value: 4
second_hidden:
  value: 100
