wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.3223410982060389
dv:
  value: 3
input_dropout:
  value: 0.5615336527424474
layers:
  value: 2
learning_rate:
  value: 0.01
