wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.30901549142899043
dv:
  value: 2
input_dropout:
  value: 0.42812775307559103
layers:
  value: 3
learning_rate:
  value: 0.01
