wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.4003449595145695
dv:
  value: 3
input_dropout:
  value: 0.6226926117833311
layers:
  value: 6
learning_rate:
  value: 0.01
