wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.5151324050623128
dv:
  value: 2
input_dropout:
  value: 0.7661062457016516
layers:
  value: 4
learning_rate:
  value: 0.01
