wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.2857506129838999
dv:
  value: 2
input_dropout:
  value: 0.6090384794952828
layers:
  value: 6
learning_rate:
  value: 0.01
