wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.841001758869319
dv:
  value: 2
input_dropout:
  value: 0.466966450047824
layers:
  value: 2
learning_rate:
  value: 0.01
