wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.41388689904886033
dv:
  value: 4
input_dropout:
  value: 0.644383694797812
layers:
  value: 6
learning_rate:
  value: 0.01
