wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.530537434242008
dv:
  value: 4
input_dropout:
  value: 0.49286258390508697
layers:
  value: 2
learning_rate:
  value: 0.01
