wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.8916568488082284
dv:
  value: 4
input_dropout:
  value: 0.6696542517768498
layers:
  value: 3
learning_rate:
  value: 0.01
