wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.7346023851145442
dv:
  value: 3
input_dropout:
  value: 0.14390280185543292
layers:
  value: 7
learning_rate:
  value: 0.01
