wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.45567933649054193
dv:
  value: 5
input_dropout:
  value: 0.5472979744198722
layers:
  value: 2
learning_rate:
  value: 0.01
