wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.14044774146665084
dv:
  value: 2
input_dropout:
  value: 0.4289565698008917
layers:
  value: 5
learning_rate:
  value: 0.01
