wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.6412766550424671
dv:
  value: 3
input_dropout:
  value: 0.8708191838071718
layers:
  value: 7
learning_rate:
  value: 0.01
