wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.3658042558506297
dv:
  value: 3
input_dropout:
  value: 0.49392514973131063
layers:
  value: 5
learning_rate:
  value: 0.01
