wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.25165052462370585
dv:
  value: 3
input_dropout:
  value: 0.5892737997758303
layers:
  value: 7
learning_rate:
  value: 0.01
