wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.572025248414832
dv:
  value: 5
input_dropout:
  value: 0.12941678762423986
layers:
  value: 2
learning_rate:
  value: 0.01
