wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.1509999754702876
dv:
  value: 5
input_dropout:
  value: 0.29851825171986823
layers:
  value: 6
learning_rate:
  value: 0.01
