wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.22290253790159417
dv:
  value: 2
input_dropout:
  value: 0.15351838939415582
layers:
  value: 7
learning_rate:
  value: 0.01
