wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.4722226874441828
dv:
  value: 4
input_dropout:
  value: 0.8603171304380213
layers:
  value: 4
learning_rate:
  value: 0.01
