wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.8773606069605465
dv:
  value: 4
input_dropout:
  value: 0.28837623144671626
layers:
  value: 3
learning_rate:
  value: 0.01
