wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.5741094394153057
dv:
  value: 5
input_dropout:
  value: 0.7843523796893341
layers:
  value: 4
learning_rate:
  value: 0.01
