wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 4
dropout:
  value: 0.2752829482746396
dv:
  value: 4
input_dropout:
  value: 0.6497464105778704
layers:
  value: 4
learning_rate:
  value: 0.01
