wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.6518131691942559
dv:
  value: 3
input_dropout:
  value: 0.3380811934418697
layers:
  value: 4
learning_rate:
  value: 0.01
