wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.892411975739582
dv:
  value: 5
input_dropout:
  value: 0.5722483367558091
layers:
  value: 4
learning_rate:
  value: 0.01
