wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.20117150112501225
dv:
  value: 3
input_dropout:
  value: 0.6474141749756251
layers:
  value: 4
learning_rate:
  value: 0.01
