wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 4
dropout:
  value: 0.5316252978789102
dv:
  value: 5
input_dropout:
  value: 0.2500565529487518
layers:
  value: 6
learning_rate:
  value: 0.01
