wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.28508342132741105
dv:
  value: 3
input_dropout:
  value: 0.4367747620603398
layers:
  value: 6
learning_rate:
  value: 0.01
