wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.8657055849595473
dv:
  value: 3
input_dropout:
  value: 0.3072734578134756
layers:
  value: 2
learning_rate:
  value: 0.01
