wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.38166248926224267
dv:
  value: 5
input_dropout:
  value: 0.6384583796684955
layers:
  value: 2
learning_rate:
  value: 0.01
