wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 4
dropout:
  value: 0.7665925372668305
dv:
  value: 5
input_dropout:
  value: 0.1252439623794558
layers:
  value: 5
learning_rate:
  value: 0.01
