wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.26702216615606045
dv:
  value: 4
input_dropout:
  value: 0.1572313198679016
layers:
  value: 6
learning_rate:
  value: 0.01
