wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 4
dropout:
  value: 0.8354954971177814
dv:
  value: 4
input_dropout:
  value: 0.8039474906953339
layers:
  value: 6
learning_rate:
  value: 0.01
