wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 4
dropout:
  value: 0.15283501198451016
dv:
  value: 2
input_dropout:
  value: 0.6779269616358821
layers:
  value: 6
learning_rate:
  value: 0.01
