wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.22572158858318972
dv:
  value: 2
input_dropout:
  value: 0.526866402737326
layers:
  value: 4
learning_rate:
  value: 0.01
