wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.5379286556883653
dv:
  value: 5
input_dropout:
  value: 0.759669722766486
layers:
  value: 5
learning_rate:
  value: 0.01
