wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 4
dropout:
  value: 0.19265166046242277
dv:
  value: 5
input_dropout:
  value: 0.7368928284481203
layers:
  value: 3
learning_rate:
  value: 0.01
