wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.30311230794018207
dv:
  value: 4
input_dropout:
  value: 0.8148415455802985
layers:
  value: 2
learning_rate:
  value: 0.01
