wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.3965054260738756
dv:
  value: 2
input_dropout:
  value: 0.8967032463074499
layers:
  value: 3
learning_rate:
  value: 0.01
