wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.7264317005746322
dv:
  value: 5
input_dropout:
  value: 0.4846104494591851
layers:
  value: 3
learning_rate:
  value: 0.01
