wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.20784704279157387
dv:
  value: 4
input_dropout:
  value: 0.8018513417060279
layers:
  value: 5
learning_rate:
  value: 0.01
