wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.7713149862694805
dv:
  value: 3
input_dropout:
  value: 0.7864117915595009
layers:
  value: 4
learning_rate:
  value: 0.01
