wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.6495305512341986
dv:
  value: 3
input_dropout:
  value: 0.7070669503392846
layers:
  value: 5
learning_rate:
  value: 0.01
