wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.3317089848465302
dv:
  value: 4
input_dropout:
  value: 0.21644905020317415
layers:
  value: 6
learning_rate:
  value: 0.01
