wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.11312061847280389
dv:
  value: 5
input_dropout:
  value: 0.3048874150538854
layers:
  value: 6
learning_rate:
  value: 0.01
