wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.3986739005657247
dv:
  value: 4
input_dropout:
  value: 0.858683363412616
layers:
  value: 5
learning_rate:
  value: 0.01
