wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.7579720729868981
dv:
  value: 4
input_dropout:
  value: 0.39805418656139335
layers:
  value: 6
learning_rate:
  value: 0.01
