wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.8440259747660749
dv:
  value: 2
input_dropout:
  value: 0.23405062296631104
layers:
  value: 6
learning_rate:
  value: 0.01
