wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.7481366556330612
dv:
  value: 3
input_dropout:
  value: 0.32357579637533895
layers:
  value: 4
learning_rate:
  value: 0.01
