wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.7512382530576334
dv:
  value: 5
input_dropout:
  value: 0.2251143151150248
layers:
  value: 5
learning_rate:
  value: 0.01
