wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.4296396643171349
dv:
  value: 3
input_dropout:
  value: 0.7828064793123599
layers:
  value: 5
learning_rate:
  value: 0.01
