wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.124776352463498
dv:
  value: 4
input_dropout:
  value: 0.2536222766472716
layers:
  value: 2
learning_rate:
  value: 0.01
