wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.7337135318449385
dv:
  value: 5
input_dropout:
  value: 0.15192122891731624
layers:
  value: 2
learning_rate:
  value: 0.01
