wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.5440471423661039
dv:
  value: 4
input_dropout:
  value: 0.594978713316897
layers:
  value: 7
learning_rate:
  value: 0.01
