wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.29563991949958024
dv:
  value: 3
input_dropout:
  value: 0.4400779438158742
layers:
  value: 6
learning_rate:
  value: 0.01
