wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.23267164996277476
dv:
  value: 4
input_dropout:
  value: 0.7480073278642658
layers:
  value: 3
learning_rate:
  value: 0.01
