wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.6478938630458516
dv:
  value: 4
input_dropout:
  value: 0.8065438311345267
layers:
  value: 2
learning_rate:
  value: 0.01
