wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.6754219926357963
dv:
  value: 4
input_dropout:
  value: 0.4510602947486766
layers:
  value: 2
learning_rate:
  value: 0.01
