wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.8861558578206972
dv:
  value: 4
input_dropout:
  value: 0.1182429855470919
layers:
  value: 2
learning_rate:
  value: 0.01
