wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.2949301597599403
dv:
  value: 2
input_dropout:
  value: 0.5403507711918826
layers:
  value: 2
learning_rate:
  value: 0.01
