wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.22848143301554355
dv:
  value: 4
input_dropout:
  value: 0.4336327857898451
layers:
  value: 2
learning_rate:
  value: 0.01
