wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.2272223196182855
dv:
  value: 2
input_dropout:
  value: 0.5021996316822651
layers:
  value: 7
learning_rate:
  value: 0.01
