wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.40131554031231687
dv:
  value: 2
input_dropout:
  value: 0.6636914650733241
layers:
  value: 2
learning_rate:
  value: 0.01
