wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.5283717253710196
dv:
  value: 5
input_dropout:
  value: 0.7602156907798941
layers:
  value: 6
learning_rate:
  value: 0.01
