wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.31195159931260574
dv:
  value: 2
input_dropout:
  value: 0.631464355865214
layers:
  value: 3
learning_rate:
  value: 0.01
