wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.7705080832956359
dv:
  value: 2
input_dropout:
  value: 0.7104679666100179
layers:
  value: 4
learning_rate:
  value: 0.01
