wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.4826373837125967
dv:
  value: 4
input_dropout:
  value: 0.5046564120911045
layers:
  value: 7
learning_rate:
  value: 0.01
