wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.2918698482466524
dv:
  value: 5
input_dropout:
  value: 0.5644941477982899
layers:
  value: 4
learning_rate:
  value: 0.01
