wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.4279215946320501
dv:
  value: 2
input_dropout:
  value: 0.1770666887188365
layers:
  value: 4
learning_rate:
  value: 0.01
