wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.6616509452532406
dv:
  value: 5
input_dropout:
  value: 0.7875067868972639
layers:
  value: 3
learning_rate:
  value: 0.01
