wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.7411531024368407
dv:
  value: 4
input_dropout:
  value: 0.4707087923823482
layers:
  value: 7
learning_rate:
  value: 0.01
