wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.17293741036515353
dv:
  value: 2
input_dropout:
  value: 0.721242535511736
layers:
  value: 7
learning_rate:
  value: 0.01
