wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.1556723103970848
dv:
  value: 3
input_dropout:
  value: 0.8367698046025502
layers:
  value: 7
learning_rate:
  value: 0.01
