wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.2156659862215934
dv:
  value: 2
input_dropout:
  value: 0.3717324160260472
layers:
  value: 7
learning_rate:
  value: 0.01
