wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.24542194833541145
dv:
  value: 5
input_dropout:
  value: 0.6956729988124587
layers:
  value: 7
learning_rate:
  value: 0.01
