wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.15943034405008635
dv:
  value: 4
input_dropout:
  value: 0.3463080392217043
layers:
  value: 2
learning_rate:
  value: 0.01
