wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.5273071526357543
dv:
  value: 5
input_dropout:
  value: 0.34271259651145014
layers:
  value: 4
learning_rate:
  value: 0.01
