wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.11842617778619403
dv:
  value: 4
input_dropout:
  value: 0.27631690245587537
layers:
  value: 7
learning_rate:
  value: 0.01
