wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.6805156879842754
dv:
  value: 4
input_dropout:
  value: 0.11878412687303604
layers:
  value: 6
learning_rate:
  value: 0.01
