wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.12238589720853704
dv:
  value: 3
input_dropout:
  value: 0.3948831286701307
layers:
  value: 5
learning_rate:
  value: 0.01
