wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 4
dropout:
  value: 0.8073108266176816
dv:
  value: 2
input_dropout:
  value: 0.10682781771497228
layers:
  value: 3
learning_rate:
  value: 0.01
