wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.29187034303250925
dv:
  value: 3
input_dropout:
  value: 0.3254427804216764
layers:
  value: 7
learning_rate:
  value: 0.01
