wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.6399717459582472
dv:
  value: 3
input_dropout:
  value: 0.5589755558165355
layers:
  value: 4
learning_rate:
  value: 0.01
