wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.79305127386709
dv:
  value: 4
input_dropout:
  value: 0.10395168844970304
layers:
  value: 3
learning_rate:
  value: 0.01
