wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.19365552812336137
dv:
  value: 3
input_dropout:
  value: 0.2856570713162072
layers:
  value: 5
learning_rate:
  value: 0.01
