wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.4321517261803186
dv:
  value: 4
input_dropout:
  value: 0.1442559232092564
layers:
  value: 2
learning_rate:
  value: 0.01
