wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.22673234859234415
dv:
  value: 2
input_dropout:
  value: 0.8815251855673714
layers:
  value: 7
learning_rate:
  value: 0.01
