wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.7478794412757435
dv:
  value: 3
input_dropout:
  value: 0.7855067663298653
layers:
  value: 7
learning_rate:
  value: 0.01
