wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.4434054215379032
dv:
  value: 5
input_dropout:
  value: 0.5781220391740995
layers:
  value: 7
learning_rate:
  value: 0.01
