wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.8670359847078565
dv:
  value: 4
input_dropout:
  value: 0.10606679991626802
layers:
  value: 7
learning_rate:
  value: 0.01
