wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.511877073327456
dv:
  value: 2
input_dropout:
  value: 0.8651748731721404
layers:
  value: 2
learning_rate:
  value: 0.01
