wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.15229808805625542
dv:
  value: 2
input_dropout:
  value: 0.17838331513054656
layers:
  value: 2
learning_rate:
  value: 0.01
