wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.6741307982287201
dv:
  value: 5
input_dropout:
  value: 0.3867847932816151
layers:
  value: 6
learning_rate:
  value: 0.01
