wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.19829495714412976
dv:
  value: 5
input_dropout:
  value: 0.1152509494600774
layers:
  value: 5
learning_rate:
  value: 0.01
