wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.5746437462944838
dv:
  value: 3
input_dropout:
  value: 0.8398026761127748
layers:
  value: 7
learning_rate:
  value: 0.01
