wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 4
dropout:
  value: 0.6253493473539496
dv:
  value: 3
input_dropout:
  value: 0.695927489874048
layers:
  value: 4
learning_rate:
  value: 0.01
