wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.6633524930092624
dv:
  value: 4
input_dropout:
  value: 0.11420280133278782
layers:
  value: 7
learning_rate:
  value: 0.01
