wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.4815274064330619
dv:
  value: 4
input_dropout:
  value: 0.4404477531954444
layers:
  value: 3
learning_rate:
  value: 0.01
