wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.3431350559741787
dv:
  value: 2
input_dropout:
  value: 0.7722369289292689
layers:
  value: 3
learning_rate:
  value: 0.01
