wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.734269034747017
dv:
  value: 5
input_dropout:
  value: 0.6168048415634187
layers:
  value: 5
learning_rate:
  value: 0.01
