wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.7919236553401449
dv:
  value: 2
input_dropout:
  value: 0.4652866570830744
layers:
  value: 6
learning_rate:
  value: 0.01
