wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.8763625435322518
dv:
  value: 4
input_dropout:
  value: 0.48538958789264697
layers:
  value: 2
learning_rate:
  value: 0.01
