wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.3625669110013843
dv:
  value: 4
input_dropout:
  value: 0.2550073601699424
layers:
  value: 6
learning_rate:
  value: 0.01
