wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.1335540403659306
dv:
  value: 4
input_dropout:
  value: 0.4396360433024942
layers:
  value: 2
learning_rate:
  value: 0.01
