wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.3672529237786055
dv:
  value: 4
input_dropout:
  value: 0.8584938577414375
layers:
  value: 4
learning_rate:
  value: 0.01
