wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.3154118595042871
dv:
  value: 2
input_dropout:
  value: 0.5493215846275837
layers:
  value: 6
learning_rate:
  value: 0.01
