wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.2753827424852672
dv:
  value: 5
input_dropout:
  value: 0.7858174279653056
layers:
  value: 2
learning_rate:
  value: 0.01
