wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.27258229557607494
dv:
  value: 3
input_dropout:
  value: 0.3983914722600924
layers:
  value: 6
learning_rate:
  value: 0.01
