wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.5951086146917808
dv:
  value: 4
input_dropout:
  value: 0.7362828855272099
layers:
  value: 5
learning_rate:
  value: 0.01
