wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.27288028730039465
dv:
  value: 3
input_dropout:
  value: 0.6312417724932234
layers:
  value: 7
learning_rate:
  value: 0.01
