wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.89467099040402
dv:
  value: 4
input_dropout:
  value: 0.6215555454272645
layers:
  value: 2
learning_rate:
  value: 0.01
