wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.3199715377169386
dv:
  value: 4
input_dropout:
  value: 0.8064571751262783
layers:
  value: 6
learning_rate:
  value: 0.01
