wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.44973573189357374
dv:
  value: 3
input_dropout:
  value: 0.36744253472728794
layers:
  value: 7
learning_rate:
  value: 0.01
