wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.896497608721947
dv:
  value: 4
input_dropout:
  value: 0.5686955221305225
layers:
  value: 4
learning_rate:
  value: 0.01
