wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.817232638555048
dv:
  value: 5
input_dropout:
  value: 0.4860866929202604
layers:
  value: 2
learning_rate:
  value: 0.01
