wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.2574393844271403
dv:
  value: 3
input_dropout:
  value: 0.16805854373960205
layers:
  value: 3
learning_rate:
  value: 0.01
