wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.3913867009651846
dv:
  value: 2
input_dropout:
  value: 0.5195946955264523
layers:
  value: 3
learning_rate:
  value: 0.01
