wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.8117262542420635
dv:
  value: 2
input_dropout:
  value: 0.5645141179196699
layers:
  value: 6
learning_rate:
  value: 0.01
