wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.5164400230955397
dv:
  value: 5
input_dropout:
  value: 0.1772634863465462
layers:
  value: 3
learning_rate:
  value: 0.01
