wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.2708666055151239
dv:
  value: 5
input_dropout:
  value: 0.6989994369647816
layers:
  value: 2
learning_rate:
  value: 0.01
