wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.11955560106011703
dv:
  value: 3
input_dropout:
  value: 0.8304569760165964
layers:
  value: 2
learning_rate:
  value: 0.01
