wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.1005456049435118
dv:
  value: 5
input_dropout:
  value: 0.14255988784132756
layers:
  value: 4
learning_rate:
  value: 0.01
