wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.33533539651998484
dv:
  value: 5
input_dropout:
  value: 0.5863444928031148
layers:
  value: 2
learning_rate:
  value: 0.01
