wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.3011228776684363
dv:
  value: 3
input_dropout:
  value: 0.3319760214172871
layers:
  value: 5
learning_rate:
  value: 0.01
