wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 4
dropout:
  value: 0.81080247750347
dv:
  value: 2
input_dropout:
  value: 0.5702822310198735
layers:
  value: 4
learning_rate:
  value: 0.01
