wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.8533992079840707
dv:
  value: 3
input_dropout:
  value: 0.4019429561832534
layers:
  value: 4
learning_rate:
  value: 0.01
