wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.25908306080272503
dv:
  value: 3
input_dropout:
  value: 0.724633639296758
layers:
  value: 5
learning_rate:
  value: 0.01
