wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.7832262475576698
dv:
  value: 5
input_dropout:
  value: 0.7054047004693101
layers:
  value: 5
learning_rate:
  value: 0.01
