wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.5944168104500168
dv:
  value: 5
input_dropout:
  value: 0.3346413350676126
layers:
  value: 5
learning_rate:
  value: 0.01
