wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.5699000266167711
dv:
  value: 3
input_dropout:
  value: 0.5787598099865693
layers:
  value: 3
learning_rate:
  value: 0.01
