wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.7696089646773968
dv:
  value: 5
input_dropout:
  value: 0.4478228988473356
layers:
  value: 2
learning_rate:
  value: 0.01
