wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.5309865768832276
dv:
  value: 3
input_dropout:
  value: 0.6283710441950967
layers:
  value: 7
learning_rate:
  value: 0.01
