wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 4
dropout:
  value: 0.25010595160568816
dv:
  value: 5
input_dropout:
  value: 0.33661895177237644
layers:
  value: 4
learning_rate:
  value: 0.01
