wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.12496784069463232
dv:
  value: 3
input_dropout:
  value: 0.5599254277215999
layers:
  value: 7
learning_rate:
  value: 0.01
