wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 2
dropout:
  value: 0.7587294863419216
dv:
  value: 5
input_dropout:
  value: 0.3094376645634217
layers:
  value: 7
learning_rate:
  value: 0.01
