wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.5473916941960808
dv:
  value: 5
input_dropout:
  value: 0.7536533731364858
layers:
  value: 5
learning_rate:
  value: 0.01
