wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.6853151280716294
dv:
  value: 4
input_dropout:
  value: 0.8644038011394389
layers:
  value: 4
learning_rate:
  value: 0.01
