wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.2466280033240256
dv:
  value: 5
input_dropout:
  value: 0.4483767581952043
layers:
  value: 7
learning_rate:
  value: 0.01
