wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 2
dropout:
  value: 0.663557734979191
dv:
  value: 3
input_dropout:
  value: 0.7161191747484057
layers:
  value: 7
learning_rate:
  value: 0.01
