wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.6037022941411008
dv:
  value: 2
input_dropout:
  value: 0.17005803963746963
layers:
  value: 6
learning_rate:
  value: 0.01
