wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.13083254144944548
dv:
  value: 2
input_dropout:
  value: 0.6858502041958575
layers:
  value: 4
learning_rate:
  value: 0.01
