wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 3
dropout:
  value: 0.38632935532867674
dv:
  value: 3
input_dropout:
  value: 0.23823880559627533
layers:
  value: 7
learning_rate:
  value: 0.01
