wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.8070400758373205
dv:
  value: 2
input_dropout:
  value: 0.688081232991695
layers:
  value: 2
learning_rate:
  value: 0.01
