wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.11055290751849736
dv:
  value: 2
input_dropout:
  value: 0.45231562105109224
layers:
  value: 5
learning_rate:
  value: 0.01
