wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 4
dropout:
  value: 0.8090017031230812
dv:
  value: 4
input_dropout:
  value: 0.11729700610483064
layers:
  value: 5
learning_rate:
  value: 0.01
