wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 3
dropout:
  value: 0.8678523550825731
dv:
  value: 5
input_dropout:
  value: 0.6392480554225877
layers:
  value: 6
learning_rate:
  value: 0.01
