wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 3
dropout:
  value: 0.5397259595002434
dv:
  value: 5
input_dropout:
  value: 0.2406921172114883
layers:
  value: 2
learning_rate:
  value: 0.01
