wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 2
dropout:
  value: 0.1875360860312715
dv:
  value: 2
input_dropout:
  value: 0.7535139424164389
layers:
  value: 7
learning_rate:
  value: 0.01
