wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 5
dropout:
  value: 0.17951616494569703
dv:
  value: 2
input_dropout:
  value: 0.28993678084208374
layers:
  value: 3
learning_rate:
  value: 0.01
