wandb_version: 1

batch_size:
  value: 60
channels:
  value: 3
de:
  value: 4
dropout:
  value: 0.14244987335194192
dv:
  value: 2
input_dropout:
  value: 0.10146282415592066
layers:
  value: 4
learning_rate:
  value: 0.01
