wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 2
dropout:
  value: 0.7441637886461127
dv:
  value: 3
input_dropout:
  value: 0.5990172438655158
layers:
  value: 4
learning_rate:
  value: 0.01
