wandb_version: 1

batch_size:
  value: 60
channels:
  value: 2
de:
  value: 5
dropout:
  value: 0.16274696129403016
dv:
  value: 4
input_dropout:
  value: 0.7343755624405266
layers:
  value: 5
learning_rate:
  value: 0.01
