wandb_version: 1

batch_size:
  value: 240
channels:
  value: 5
de:
  value: 5
dropout:
  value: 0.34101554874309703
dv:
  value: 3
input_dropout:
  value: 0.6240364006522736
layers:
  value: 4
learning_rate:
  value: 0.01
