wandb_version: 1

Ne:
  desc: null
  value: 558
Nv:
  desc: null
  value: 183
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1670206587.987174
    t:
      1:
      - 1
      - 9
      - 55
      - 77
      2:
      - 1
      - 9
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.13.5
      8:
      - 1
      - 5
add_hp:
  desc: null
  value: true
add_lp:
  desc: null
  value: true
augmented:
  desc: null
  value: true
batch_size:
  desc: null
  value: 60
channels:
  desc: null
  value: 2
de:
  desc: null
  value: 3
dropout:
  desc: null
  value: 0.5946494164261176
dv:
  desc: null
  value: 2
graph:
  desc: null
  value: DiGraph with 183 nodes and 558 edges
input_dim:
  desc: null
  value: 1703
input_dropout:
  desc: null
  value: 0.8108828976140946
layers:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.01
left_weights:
  desc: null
  value: true
mask/test_mask:
  desc: null
  value: "[False False False False False False False False False False  True False\n\
    \ False False  True False False  True False False  True False  True False\n False\
    \ False False False False  True  True  True False False False False\n False False\
    \ False False False False False False False False False False\n False  True False\
    \  True False False  True False  True  True False False\n False False False False\
    \ False False False False  True False False False\n False False False False False\
    \ False False  True  True  True False False\n  True False False False False False\
    \  True False False False False False\n False  True False  True False False  True\
    \ False False False False False\n False False False False False False False False\
    \ False  True False False\n False False False False False False False False False\
    \  True False False\n  True False False False  True False False False False False\
    \ False  True\n False False False False False False  True  True False False False\
    \  True\n False  True  True False False False False False  True  True False False\n\
    \ False  True False False  True False False False False False  True False\n False\
    \ False False]"
mask/train_mask:
  desc: null
  value: "[ True False  True False  True False False False  True False False  True\n\
    \ False  True False  True False False False  True False  True False False\n False\
    \ False  True False False False False False  True False False  True\n False  True\
    \ False  True False  True False False  True  True  True False\n False False  True\
    \ False False  True False False False False  True  True\n  True  True False  True\
    \ False  True  True False False False  True  True\n  True  True  True  True  True\
    \  True  True False False False False  True\n False  True  True False  True  True\
    \ False False  True False  True  True\n  True False False False False  True False\
    \  True  True  True False  True\n  True False  True False False  True False  True\
    \  True False False  True\n  True  True False  True  True  True  True False False\
    \ False  True  True\n False  True False  True False  True False  True  True  True\
    \  True False\n  True  True  True False  True False False False  True  True False\
    \ False\n  True False False False False  True False False False False False False\n\
    \  True False  True  True False  True False False False  True False  True\n False\
    \  True  True]"
mask/val_mask:
  desc: null
  value: "[False  True False  True False  True  True  True False  True False False\n\
    \  True False False False  True False  True False False False False  True\n  True\
    \  True False  True  True False False False False  True  True False\n  True False\
    \  True False  True False  True  True False False False  True\n  True False False\
    \ False  True False False  True False False False False\n False False  True False\
    \  True False False  True False  True False False\n False False False False False\
    \ False False False False False  True False\n False False False  True False False\
    \ False  True False  True False False\n False False  True False  True False False\
    \ False False False  True False\n False  True False  True  True False  True False\
    \ False False  True False\n False False  True False False False False  True  True\
    \ False False False\n False False  True False False False  True False False False\
    \ False False\n False False False  True False  True False False False False  True\
    \ False\n False False False  True  True False  True  True False False  True  True\n\
    \ False False False False False False  True  True  True False False False\n  True\
    \ False False]"
output_dim:
  desc: null
  value: 5
potential:
  desc: null
  value: radial
right_weights:
  desc: null
  value: true
use_act:
  desc: null
  value: true
