wandb_version: 1

batch_size:
  value: 60
channels:
  value: 4
de:
  value: 5
dropout:
  value: 0.25329006204143434
dv:
  value: 3
first_hidden:
  value: 1000
free_potential:
  value: true
input_dropout:
  value: 0.5820397641859126
layers:
  value: 2
second_hidden:
  value: 1000
