wandb_version: 1

batch_size:
  value: 60
channels:
  value: 5
de:
  value: 3
dropout:
  value: 0.22338891251869825
dv:
  value: 2
first_hidden:
  value: 100
free_potential:
  value: false
input_dropout:
  value: 0.4594563945213752
layers:
  value: 2
second_hidden:
  value: 1000
